window.addEventListener("error",function(e){showStartupError("JavaScript error",e.message,(e.filename||"").split("/").pop(),e.lineno,e.colno)});window.addEventListener("unhandledrejection",function(e){showStartupError("Unhandled error",e.reason&&e.reason.message?e.reason.message:String(e.reason))});function showStartupError(){var parts=Array.prototype.slice.call(arguments).filter(Boolean),box=document.getElementById("startupError");if(!box){box=document.createElement("div");box.id="startupError";box.style.cssText="position:fixed;z-index:99999;left:12px;right:12px;top:12px;padding:14px;background:#5b1010;color:white;border:2px solid #ff7b7b;border-radius:10px;font:14px/1.4 monospace;white-space:pre-wrap;overflow-wrap:anywhere";document.body.appendChild(box)}box.textContent="GameVault startup error\n"+parts.join(" | ")}
const seedGames=[
{id:"diablo4",title:"Diablo IV",platform:"PC",active:true},
{id:"dragonwilds",title:"RuneScape: Dragonwilds",platform:"Xbox",active:true},
{id:"aniimo",title:"Aniimo",platform:"PC / Xbox",active:true},
{id:"wow",title:"World of Warcraft",platform:"PC",active:true},
{id:"botw",title:"The Legend of Zelda: Breath of the Wild",platform:"Switch",active:true},
{id:"minecraft",title:"Minecraft",platform:"PC",active:true}
];
const seedPlays=[
{id:"d4-stinger",gameId:"diablo4",name:"Spiritborn • Stinger",meta:"Level 70",resume:"Transition from the Stinger leveling build into your first endgame setup.",goal:"Build an all-purpose Stinger setup for broad endgame content.",active:true,updated:6},
{id:"dw-emberfall",gameId:"dragonwilds",name:"Emberfall",meta:"Co-op",resume:"Continue later-region progression with your friend.",goal:"Advance quests and keep gear and skill progression moving together.",active:true,updated:5},
{id:"aniimo-main",gameId:"aniimo",name:"Main Journey",meta:"Wayfarer progression",resume:"Continue post-story progression and establish a daily/weekly routine.",goal:"Level efficiently and focus on PvE and battle-ready Aniimo.",active:true,updated:4},
{id:"wow-kovaru",gameId:"wow",name:"Kovaru",meta:"Beast Mastery Hunter",resume:"Continue Kovaru's progression.",goal:"Keep leveling with the controller-friendly setup.",active:true,updated:3},
{id:"botw-fresh",gameId:"botw",name:"Fresh Playthrough",meta:"All DLC",resume:"Great Plateau: work toward the Warm Doublet.",goal:"Prepare this save as the foundation for a future TotK run.",active:true,updated:2},
{id:"mc-fabric",gameId:"minecraft",name:"Fabric Survival",meta:"Custom zombie mod",resume:"Zombie call-for-help mod works; stress testing remains.",goal:"Finish mod testing and continue the survival world.",active:true,updated:1}
];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function migrate(){let games=read("gv_games",null);if(!games){write("gv_games",seedGames);write("gv_playthroughs",seedPlays);return}if(!localStorage.getItem("gv_playthroughs")){const plays=games.map((g,i)=>({id:g.id+"-main",gameId:g.id,name:(g.meta||"Playthrough").split(" • ")[0]||"Main Playthrough",meta:(g.meta||"").split(" • ").slice(1).join(" • "),resume:g.resume||"",goal:g.goal||"",active:g.active!==false,updated:games.length-i}));write("gv_playthroughs",plays);write("gv_games",games.map(g=>({id:g.id,title:g.title,platform:g.platform,active:g.active!==false})));}}
migrate();
const store={
get games(){return read("gv_games",seedGames)},set games(v){write("gv_games",v)},
get plays(){return read("gv_playthroughs",seedPlays)},set plays(v){write("gv_playthroughs",v)},
get tasks(){return read("gv_tasks",[])},set tasks(v){write("gv_tasks",v)},
get notes(){return read("gv_notes",[])},set notes(v){write("gv_notes",v)},
get resources(){return read("gv_resources",[])},set resources(v){write("gv_resources",v)}
};
const view=document.querySelector("#view"),pageTitle=document.querySelector("#pageTitle");function esc(value){return String(value==null?"":value).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
const gameOf=p=>store.games.find(g=>g.id===p.gameId),playsFor=id=>store.plays.filter(p=>p.gameId===id),currentPlay=id=>playsFor(id).find(p=>p.active)||playsFor(id)[0];function setCurrentPlay(id){const target=store.plays.find(p=>p.id===id);if(!target)return;store.plays=store.plays.map(p=>p.gameId===target.gameId?{...p,active:p.id===id}:p);route()}
function playCard(p){const g=gameOf(p);return '<article class="card" data-play="'+p.id+'"><span class="platform">'+esc(g?.platform)+'</span><h3>'+esc(g?.title)+'</h3><p class="muted">'+esc(p.name)+(p.meta?" • "+esc(p.meta):"")+'</p><div class="resume-small"><b>Resume:</b> '+esc(p.resume||"No resume point yet.")+'</div></article>'}
function gameCard(g){const ps=playsFor(g.id),p=currentPlay(g.id);return '<article class="card" data-game="'+g.id+'"><span class="platform">'+esc(g.platform)+'</span><h3>'+esc(g.title)+'</h3><p class="muted">'+ps.length+' playthrough'+(ps.length===1?"":"s")+'</p><div class="resume-small"><b>Current:</b> '+esc(p?.name||"No playthrough yet")+'</div></article>'}
function taskRow(t){const p=store.plays.find(x=>x.id===t.playId),g=p?gameOf(p):store.games.find(x=>x.id===t.gameId);return '<div class="task"><button class="check" data-task="'+t.id+'" aria-label="Complete task"></button><div><b>'+esc(t.text)+'</b><small>'+esc(g?.title||"Game")+(p?" • "+esc(p.name):"")+'</small></div><button class="delete-mini" data-delete-task="'+t.id+'" aria-label="Delete task">Delete</button></div>'}
function home(){const ps=store.plays.filter(p=>p&&p.active&&gameOf(p)).sort((a,b)=>(b.updated||0)-(a.updated||0)),lead=ps[0],g=lead?gameOf(lead):null,tasks=store.tasks.filter(t=>t&&!t.done).slice(0,5);pageTitle.textContent="Home";view.innerHTML=lead?'<section class="hero"><div class="hero-content"><span class="badge">CONTINUE PLAYING</span><h2>'+esc(g.title)+'</h2><p class="muted">'+esc(lead.name)+(lead.meta?" • "+esc(lead.meta):"")+'</p><div class="resume"><span class="eyebrow">RESUME HERE</span><span class="resume-text">'+esc(lead.resume||"Nothing captured yet.")+'</span></div><button class="primary" data-play="'+lead.id+'">Open playthrough</button></div></section><div class="section-head"><h2>Active playthroughs</h2><a href="#games">View library →</a></div><div class="game-grid">'+ps.slice(0,6).map(playCard).join("")+'</div><div class="section-head"><h2>Up next</h2><a href="#tasks">All tasks →</a></div>'+(tasks.length?'<div class="task-list">'+tasks.map(taskRow).join("")+'</div>':'<div class="empty">No tasks yet. Use ＋ to capture your next objective.</div>'):'<div class="empty">Add a game and playthrough to get started.</div>';bind()}
function games(){pageTitle.textContent="Games";view.innerHTML='<div class="section-head"><div><p class="eyebrow">YOUR LIBRARY</p><h2>All games</h2></div><button class="primary" id="newGame">＋ Add game</button></div><div class="game-grid">'+store.games.map(gameCard).join("")+'</div>';bind();document.querySelector("#newGame").onclick=()=>openManage("game")}
function game(id){const g=store.games.find(x=>x.id===id);if(!g){location.hash="#games";return}pageTitle.textContent=g.title;const ps=playsFor(id);view.innerHTML='<a class="back" href="#games">← Library</a><div class="section-head"><div><p class="eyebrow">'+esc(g.platform)+'</p><h2>'+esc(g.title)+'</h2><p class="muted">'+ps.length+' playthrough'+(ps.length===1?"":"s")+'</p></div><div class="actions"><button class="secondary" data-edit-game="'+g.id+'">Edit game</button><button class="primary" data-new-play="'+g.id+'">＋ Playthrough</button></div></div>'+(ps.length?'<div class="game-grid">'+ps.map(p=>'<article class="card" data-play="'+p.id+'"><span class="platform">'+(p.active?"CURRENT":"PLAYTHROUGH")+'</span><h3>'+esc(p.name)+'</h3><p class="muted">'+esc(p.meta||"")+'</p><div class="resume-small"><b>Resume:</b> '+esc(p.resume||"Nothing captured yet.")+'</div>'+(p.active?'':'<button class="set-current" data-current-play="'+p.id+'">Set as Current</button>')+'</article>').join("")+'</div>':'<div class="empty">No playthroughs yet. Create one to start tracking this game.</div>');bind()}
function play(id,tab="overview"){const p=store.plays.find(x=>x.id===id);if(!p){location.hash="#games";return}const g=gameOf(p),ts=store.tasks.filter(t=>!t.done&&(t.playId===id||(!t.playId&&t.gameId===g.id))),ns=store.notes.filter(n=>n.playId===id||(!n.playId&&n.gameId===g.id)),rs=store.resources.filter(r=>r.playId===id);pageTitle.textContent=p.name;view.innerHTML='<a class="back" href="#game/'+g.id+'">← '+esc(g.title)+'</a><div class="section-head"><div><p class="eyebrow">'+esc(g.platform)+'</p><h2>'+esc(p.name)+'</h2><p class="muted">'+esc(p.meta||"")+'</p></div><button class="secondary" data-edit-play="'+p.id+'">Edit</button></div><div class="tabs"><button class="tab '+(tab==="overview"?"active":"")+'" data-ptab="overview">Overview</button><button class="tab '+(tab==="tasks"?"active":"")+'" data-ptab="tasks">Tasks '+(ts.length?"("+ts.length+")":"")+'</button><button class="tab '+(tab==="notes"?"active":"")+'" data-ptab="notes">Notes '+(ns.length?"("+ns.length+")":"")+'</button><button class="tab '+(tab==="resources"?"active":"")+'" data-ptab="resources">Resources</button></div><div id="tabBody"></div>';const body=document.querySelector("#tabBody");if(tab==="overview")body.innerHTML='<section class="hero compact"><div class="hero-content"><p class="eyebrow">RESUME HERE</p><h3>'+esc(p.resume||"Nothing captured yet.")+'</h3><p class="eyebrow gap">CURRENT GOAL</p><p>'+esc(p.goal||"No goal set yet.")+'</p></div></section>';else if(tab==="tasks")body.innerHTML=ts.length?'<div class="task-list">'+ts.map(taskRow).join("")+'</div>':'<div class="empty">No open tasks for this playthrough.</div>';else if(tab==="notes")body.innerHTML=ns.length?'<div class="task-list">'+ns.map(n=>'<div class="task"><div><b>Note</b><small>'+esc(n.text)+'</small></div><button class="delete-mini" data-delete-note="'+n.id+'">Delete</button></div>').join("")+'</div>':'<div class="empty">No notes yet. Use ＋ to add one.</div>';else body.innerHTML='<div class="resource-head"><button class="primary" data-add-resource="'+p.id+'">＋ Add resource</button></div>'+(rs.length?'<div class="task-list">'+rs.map(r=>'<div class="task"><div><b>'+esc(r.label)+'</b><small><a class="resource-link" href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">'+esc(r.url)+'</a></small></div><button class="delete-mini" data-delete-resource="'+r.id+'">Delete</button></div>').join("")+'</div>':'<div class="empty"><h3>Resources</h3><p>No resources saved yet.</p></div>');bind()}
function tasks(){pageTitle.textContent="Tasks";const ts=store.tasks.filter(t=>!t.done);view.innerHTML='<div class="section-head"><div><p class="eyebrow">WHAT’S NEXT</p><h2>Tasks</h2></div></div>'+(ts.length?'<div class="task-list">'+ts.map(taskRow).join("")+'</div>':'<div class="empty">Nothing queued yet. Hit ＋ and add something you want to do.</div>');bind()}
function profile(){pageTitle.textContent="Profile";view.innerHTML='<div class="empty"><h2>Profile & Sync</h2><p>Accounts, cloud sync, sharing and data export will live here when Supabase is connected.</p></div>'}
function bind(){document.querySelectorAll("[data-game]").forEach(x=>x.onclick=()=>location.hash="#game/"+x.dataset.game);document.querySelectorAll("[data-play]").forEach(x=>x.onclick=()=>location.hash="#play/"+x.dataset.play);document.querySelectorAll("[data-ptab]").forEach(x=>x.onclick=()=>{const id=location.hash.split("/")[1];location.hash="#play/"+id+"/"+x.dataset.ptab});document.querySelectorAll("[data-task]").forEach(x=>x.onclick=()=>{const v=store.tasks,i=v.findIndex(t=>t.id===x.dataset.task);if(i>=0){v[i].done=true;store.tasks=v;route()}});document.querySelectorAll("[data-delete-task]").forEach(x=>x.onclick=e=>{e.stopPropagation();if(confirm("Delete this task?")){store.tasks=store.tasks.filter(t=>t.id!==x.dataset.deleteTask);route()}});document.querySelectorAll("[data-delete-note]").forEach(x=>x.onclick=e=>{e.stopPropagation();if(confirm("Delete this note?")){store.notes=store.notes.filter(n=>n.id!==x.dataset.deleteNote);route()}});document.querySelectorAll("[data-add-resource]").forEach(x=>x.onclick=()=>openResource(x.dataset.addResource));document.querySelectorAll("[data-delete-resource]").forEach(x=>x.onclick=e=>{e.stopPropagation();if(confirm("Delete this resource?")){store.resources=store.resources.filter(r=>r.id!==x.dataset.deleteResource);route()}});document.querySelectorAll("[data-current-play]").forEach(x=>x.onclick=e=>{e.stopPropagation();setCurrentPlay(x.dataset.currentPlay)});document.querySelectorAll("[data-edit-game]").forEach(x=>x.onclick=()=>openManage("game",x.dataset.editGame));document.querySelectorAll("[data-new-play]").forEach(x=>x.onclick=()=>openManage("play",null,x.dataset.newPlay));document.querySelectorAll("[data-edit-play]").forEach(x=>x.onclick=()=>openManage("play",x.dataset.editPlay))}
function route(){const [base,id,tab]=(location.hash||"#home").slice(1).split("/");document.querySelectorAll(".nav,.mnav").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+base));if(base==="games")games();else if(base==="game")game(id);else if(base==="play")play(id,tab||"overview");else if(base==="tasks")tasks();else if(base==="profile")profile();else home()}
const dlg=document.querySelector("#addDialog"),gameSelect=document.querySelector("#addGame"),playSelect=document.querySelector("#addPlay");
function openAdd(){gameSelect.innerHTML=store.games.map(g=>'<option value="'+g.id+'">'+esc(g.title)+'</option>').join("");syncPlaySelect();dlg.showModal()}
function syncPlaySelect(){const ps=playsFor(gameSelect.value);playSelect.innerHTML=ps.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("");playSelect.disabled=!ps.length}
gameSelect.onchange=syncPlaySelect;document.querySelector("#quickAdd").onclick=openAdd;document.querySelector("#mobileAdd").onclick=openAdd;document.querySelector("#saveAdd").onclick=e=>{e.preventDefault();const gameId=gameSelect.value,playId=playSelect.value,type=document.querySelector("#addType").value,text=document.querySelector("#addText").value.trim();if(!text)return;if(type==="task"){const v=store.tasks;v.unshift({id:crypto.randomUUID(),gameId,playId,text,done:false});store.tasks=v}else if(type==="note"){const v=store.notes;v.unshift({id:crypto.randomUUID(),gameId,playId,text,created:new Date().toISOString()});store.notes=v}else{const v=store.plays,i=v.findIndex(p=>p.id===playId);if(i>=0){v[i].resume=text;v[i].updated=Date.now()}store.plays=v}document.querySelector("#addText").value="";dlg.close();route()};
document.querySelector("#addDialog .icon-btn").onclick=e=>{e.preventDefault();dlg.close()};dlg.addEventListener("click",e=>{const r=dlg.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dlg.close()});
const resourceDialog=document.querySelector("#resourceDialog"),resourceForm=document.querySelector("#resourceForm");function openResource(playId){resourceForm.dataset.playId=playId;document.querySelector("#resourceLabel").value="";document.querySelector("#resourceUrl").value="";resourceDialog.showModal()}document.querySelector("#resourceClose").onclick=e=>{e.preventDefault();resourceDialog.close()};document.querySelector("#resourceSave").onclick=e=>{e.preventDefault();const playId=resourceForm.dataset.playId,p=store.plays.find(x=>x.id===playId),label=document.querySelector("#resourceLabel").value.trim(),url=document.querySelector("#resourceUrl").value.trim();if(!p||!label||!url)return;let parsed;try{parsed=new URL(url)}catch{return alert("Enter a valid URL.")}if(parsed.protocol!=="http:"&&parsed.protocol!=="https:")return alert("Resource links must use http or https.");const v=store.resources;v.unshift({id:crypto.randomUUID(),gameId:p.gameId,playId,label,url:parsed.href});store.resources=v;resourceDialog.close();play(playId,"resources")};
const manage=document.querySelector("#manageDialog"),mf=document.querySelector("#manageForm");
function openManage(kind,id=null,gameId=null){mf.dataset.kind=kind;mf.dataset.id=id||"";const isGame=kind==="game",obj=isGame?store.games.find(x=>x.id===id):store.plays.find(x=>x.id===id);document.querySelector("#manageTitle").textContent=(id?"Edit ":"New ")+(isGame?"Game":"Playthrough");document.querySelector("#mName").value=isGame?(obj?.title||""):(obj?.name||"");document.querySelector("#mPlatform").value=isGame?(obj?.platform||""):(obj?.meta||"");document.querySelector("#mPlatformLabel").textContent=isGame?"Platform":"Details";document.querySelector("#playFields").hidden=isGame;document.querySelector("#mGoal").value=obj?.goal||"";document.querySelector("#mResume").value=obj?.resume||"";mf.dataset.gameId=gameId||obj?.gameId||"";document.querySelector("#manageDelete").hidden=!id;manage.showModal()}
document.querySelector("#manageDelete").onclick=e=>{e.preventDefault();const kind=mf.dataset.kind,id=mf.dataset.id;if(!id)return;if(kind==="game"){const g=store.games.find(x=>x.id===id);if(!g||!confirm('Delete "'+g.title+'"? This will also delete all of its playthroughs, tasks, notes, and resources.'))return;const playIds=new Set(store.plays.filter(p=>p.gameId===id).map(p=>p.id));store.tasks=store.tasks.filter(t=>t.gameId!==id&&!playIds.has(t.playId));store.notes=store.notes.filter(n=>n.gameId!==id&&!playIds.has(n.playId));store.resources=store.resources.filter(r=>r.gameId!==id&&!playIds.has(r.playId));store.plays=store.plays.filter(p=>p.gameId!==id);store.games=store.games.filter(x=>x.id!==id);manage.close();location.hash="#games";route()}else{const p=store.plays.find(x=>x.id===id);if(!p||!confirm('Delete playthrough "'+p.name+'"? Its tasks, notes, and resources will also be deleted.'))return;store.tasks=store.tasks.filter(t=>t.playId!==id);store.notes=store.notes.filter(n=>n.playId!==id);store.resources=store.resources.filter(r=>r.playId!==id);store.plays=store.plays.filter(x=>x.id!==id);manage.close();location.hash="#game/"+p.gameId;route()}};
document.querySelector("#manageClose").onclick=e=>{e.preventDefault();manage.close()};manage.addEventListener("click",e=>{const r=manage.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)manage.close()});document.querySelector("#manageSave").onclick=e=>{e.preventDefault();const kind=mf.dataset.kind,id=mf.dataset.id,name=document.querySelector("#mName").value.trim(),detail=document.querySelector("#mPlatform").value.trim();if(!name)return;if(kind==="game"){const v=store.games;if(id){const i=v.findIndex(x=>x.id===id);v[i]={...v[i],title:name,platform:detail}}else v.push({id:crypto.randomUUID(),title:name,platform:detail||"Unknown",active:true});store.games=v}else{const v=store.plays;if(id){const i=v.findIndex(x=>x.id===id);v[i]={...v[i],name,meta:detail,goal:document.querySelector("#mGoal").value.trim(),resume:document.querySelector("#mResume").value.trim(),updated:Date.now()}}else{const gameId=mf.dataset.gameId,hasCurrent=v.some(p=>p.gameId===gameId&&p.active);v.push({id:crypto.randomUUID(),gameId,name,meta:detail,goal:document.querySelector("#mGoal").value.trim(),resume:document.querySelector("#mResume").value.trim(),active:!hasCurrent,updated:Date.now()})}store.plays=v}manage.close();route()};
window.addEventListener("hashchange",route);route();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
