const seed=[
{id:"diablo4",title:"Diablo IV",platform:"PC",meta:"Spiritborn • Stinger • Level 70",resume:"Transition from the Stinger leveling build into your first endgame setup.",goal:"Build an all-purpose Stinger setup for broad endgame content.",active:true},
{id:"dragonwilds",title:"RuneScape: Dragonwilds",platform:"Xbox",meta:"Emberfall • Co-op",resume:"Continue later-region progression with your friend.",goal:"Advance quests and keep gear and skill progression moving together.",active:true},
{id:"aniimo",title:"Aniimo",platform:"PC / Xbox",meta:"Wayfarer progression",resume:"Continue post-story progression and establish a daily/weekly routine.",goal:"Level efficiently and focus on PvE and battle-ready Aniimo.",active:true},
{id:"wow",title:"World of Warcraft",platform:"PC",meta:"Kovaru • Beast Mastery Hunter",resume:"Continue Kovaru's progression.",goal:"Keep leveling with the controller-friendly setup.",active:true},
{id:"botw",title:"The Legend of Zelda: Breath of the Wild",platform:"Switch",meta:"Fresh playthrough • All DLC",resume:"Great Plateau: work toward the Warm Doublet.",goal:"Prepare this save as the foundation for a future TotK run.",active:true},
{id:"minecraft",title:"Minecraft",platform:"PC",meta:"Fabric survival",resume:"Zombie call-for-help mod works; stress testing remains.",goal:"Finish mod testing and continue the survival world.",active:true}
];
const store={
 get games(){return JSON.parse(localStorage.getItem("gv_games")||"null")||seed},
 set games(v){localStorage.setItem("gv_games",JSON.stringify(v))},
 get tasks(){return JSON.parse(localStorage.getItem("gv_tasks")||"[]")},
 set tasks(v){localStorage.setItem("gv_tasks",JSON.stringify(v))},
 get notes(){return JSON.parse(localStorage.getItem("gv_notes")||"[]")},
 set notes(v){localStorage.setItem("gv_notes",JSON.stringify(v))}
};
const view=document.querySelector("#view"),title=document.querySelector("#pageTitle");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function gameCard(g){return '<article class="card" data-game="'+g.id+'"><span class="platform">'+esc(g.platform)+'</span><h3>'+esc(g.title)+'</h3><p class="muted">'+esc(g.meta)+'</p><div class="resume-small"><b>Resume:</b> '+esc(g.resume)+'</div></article>'}
function taskRow(t){const g=store.games.find(x=>x.id===t.gameId);return '<div class="task"><button class="check" data-task="'+t.id+'" aria-label="Complete task"></button><div><b>'+esc(t.text)+'</b><small>'+esc(g?.title||"Game")+'</small></div></div>'}
function home(){const games=store.games.filter(g=>g.active),lead=games[0];const tasks=store.tasks.filter(t=>!t.done).slice(0,5);title.textContent="Home";view.innerHTML='<section class="hero"><div class="hero-content"><span class="badge">CONTINUE PLAYING</span><h2>'+esc(lead.title)+'</h2><p class="muted">'+esc(lead.meta)+'</p><div class="resume"><span class="eyebrow">RESUME HERE</span>'+esc(lead.resume)+'</div><button class="primary" data-game="'+lead.id+'">Open playthrough</button></div></section><div class="section-head"><h2>Active games</h2><a href="#games">View library →</a></div><div class="game-grid">'+games.slice(0,6).map(gameCard).join("")+'</div><div class="section-head"><h2>Up next</h2><a href="#tasks">All tasks →</a></div>'+(tasks.length?'<div class="task-list">'+tasks.map(taskRow).join("")+'</div>':'<div class="empty">No tasks yet. Use ＋ to capture your next objective.</div>');bind();}
function games(){title.textContent="Games";view.innerHTML='<div class="section-head"><div><p class="eyebrow">YOUR LIBRARY</p><h2>All games</h2></div></div><div class="game-grid">'+store.games.map(gameCard).join("")+'</div>';bind()}
function tasks(){title.textContent="Tasks";const ts=store.tasks.filter(t=>!t.done);view.innerHTML='<div class="section-head"><div><p class="eyebrow">WHAT\'S NEXT</p><h2>Tasks</h2></div></div>'+(ts.length?'<div class="task-list">'+ts.map(taskRow).join("")+'</div>':'<div class="empty">Nothing queued yet. Hit ＋ and add something you want to do.</div>');bind()}
function game(id){const g=store.games.find(x=>x.id===id);if(!g)return location.hash="#games";title.textContent=g.title;const ts=store.tasks.filter(t=>t.gameId===id&&!t.done);const ns=store.notes.filter(n=>n.gameId===id);view.innerHTML='<a class="back" href="#games">← Library</a><div class="game-head"><div><p class="eyebrow">'+esc(g.platform)+'</p><h2>'+esc(g.title)+'</h2><p class="muted">'+esc(g.meta)+'</p></div></div><div class="tabs"><button class="tab active" data-tab="overview">Overview</button><button class="tab" data-tab="tasks">Tasks '+(ts.length?"("+ts.length+")":"")+'</button><button class="tab" data-tab="notes">Notes '+(ns.length?"("+ns.length+")":"")+'</button><button class="tab" data-tab="resources">Resources</button></div><section class="hero" style="min-height:220px"><div class="hero-content"><p class="eyebrow">RESUME HERE</p><h3>'+esc(g.resume)+'</h3><p class="eyebrow" style="margin-top:24px">CURRENT GOAL</p><p>'+esc(g.goal)+'</p></div></section><div class="section-head"><h2>Open tasks</h2></div>'+(ts.length?'<div class="task-list">'+ts.map(taskRow).join("")+'</div>':'<div class="empty">No open tasks for this playthrough.</div>');bind()}
function profile(){title.textContent="Profile";view.innerHTML='<div class="empty"><h2>Profile & Sync</h2><p>This is where GameVault accounts, cloud sync, sharing and data export will live when Supabase is connected.</p></div>'}
function bind(){document.querySelectorAll("[data-tab]").forEach(el=>el.onclick=()=>{const id=(location.hash.split("/")[1]||"");location.hash="#game/"+id+"/"+el.dataset.tab});document.querySelectorAll("[data-game]").forEach(el=>el.onclick=()=>location.hash="#game/"+el.dataset.game);document.querySelectorAll("[data-task]").forEach(el=>el.onclick=()=>{const ts=store.tasks,i=ts.findIndex(t=>t.id===el.dataset.task);if(i>=0){ts[i].done=true;store.tasks=ts;route()}})}
function route(){const h=(location.hash||"#home").slice(1),[base,id,tab]=h.split("/");document.querySelectorAll(".nav,.mnav").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+base));if(base==="games")games();else if(base==="tasks")tasks();else if(base==="profile")profile();else if(base==="game"){game(id);if(tab&&tab!=="overview"){const ts=store.tasks.filter(t=>t.gameId===id&&!t.done),ns=store.notes.filter(n=>n.gameId===id);document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));const hero=document.querySelector(".hero"),head=document.querySelector(".section-head"),list=head?.nextElementSibling;if(hero)hero.style.display="none";if(head)head.remove();if(list)list.remove();const box=document.createElement("div");if(tab==="tasks")box.innerHTML=ts.length?'<div class="task-list">'+ts.map(taskRow).join("")+"</div>":'<div class="empty">No open tasks for this playthrough.</div>';else if(tab==="notes")box.innerHTML=ns.length?'<div class="task-list">'+ns.map(n=>'<div class="task"><div><b>Note</b><small>'+esc(n.text)+"</small></div></div>").join("")+"</div>":'<div class="empty">No notes yet. Use ＋ to add one.</div>';else box.innerHTML='<div class="empty"><h3>Resources</h3><p>Links, guides, maps, builds and videos will live here. Resource editing is coming next.</p></div>';view.appendChild(box);bind()}}else home()}
const dlg=document.querySelector("#addDialog"),gameSelect=document.querySelector("#addGame");function openAdd(){gameSelect.innerHTML=store.games.map(g=>'<option value="'+g.id+'">'+esc(g.title)+'</option>').join("");dlg.showModal()}
document.querySelector("#quickAdd").onclick=openAdd;document.querySelector("#mobileAdd").onclick=openAdd;
document.querySelector("#saveAdd").onclick=e=>{e.preventDefault();const gameId=gameSelect.value,type=document.querySelector("#addType").value,text=document.querySelector("#addText").value.trim();if(!text)return;if(type==="task"){const v=store.tasks;v.unshift({id:crypto.randomUUID(),gameId,text,done:false});store.tasks=v}else if(type==="note"){const v=store.notes;v.unshift({id:crypto.randomUUID(),gameId,text,created:new Date().toISOString()});store.notes=v}else{const v=store.games,i=v.findIndex(g=>g.id===gameId);if(i>=0)v[i].resume=text;store.games=v}document.querySelector("#addText").value="";dlg.close();route()};
window.addEventListener("hashchange",route);route();if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js");
document.querySelector("#addDialog .icon-btn").onclick=e=>{e.preventDefault();dlg.close()};dlg.addEventListener("click",e=>{const r=dlg.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dlg.close()});
